name: Laravel Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1
    
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: restaurant
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s  --health-retries=3


    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Install composer dependencies
      run: |
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    
    - name: Prepare Laravel Application
      run: |
        php -r "file_exists('.env') || copy('.env.prod', '.env');"
        php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Database Migration
      run: php artisan migrate
      
    - name: Run Testsuit
      run: vendor/bin/phpunit tests/

    